fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: MainBundle\Entity\User
    from_email:
        address: "admin@admin.nl"
        sender_name: "Admin"