services:
#    main.example:
#        class: MainBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.form.registration:
        class: MainBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }